# Generated by Django 5.2.12 on 2026-03-30 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_id', models.CharField(default='MAHE-EGO-01', max_length=100)),
                ('weather_condition', models.CharField(default='Clear', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=4)),
                ('model_version', models.CharField(default='v1.0-fusion', max_length=100)),
                ('final_miou', models.FloatField(blank=True, null=True)),
                ('checkpoint_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField()),
                ('latency_ms', models.FloatField()),
                ('miou', models.FloatField()),
                ('pose_x', models.FloatField()),
                ('pose_y', models.FloatField()),
                ('pose_z', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='simulations.simulationsession')),
            ],
        ),
    ]
