# Generated by Django 5.2.12 on 2026-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('loss', models.FloatField()),
                ('miou', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('class_stats', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='simulations.trainingjob')),
            ],
            options={
                'ordering': ['epoch'],
            },
        ),
    ]
